Add support for podman-compose; remove PWD in volume path
change-metrics/monocle pull request #309
Opened 2021-02-25 17:35 UTC by danpawlik

With this commit, Monocle project will be able to start with
podman-compose tool.

2021-03-01 13:59 UTC, danpawlik commented
It requires some improvement, but for podman-compose site. The whole service is not working as expected.
Basic commands, how it should be executed should be very simple, like (with default variables):
```
podman run --name=monocle_elastic_1 \
           -d \
           -e ES_JAVA_OPTS="-Xms512m -Xmx512m" \
           -e discovery.type="single-node" \
           -v ./data:/usr/share/elasticsearch/data:Z \
           -p 9200:9200 \
           --add-host api:127.0.0.1 \
           --add-host monocle_api_1:127.0.0.1 \
           --add-host elastic:127.0.0.1 \
           --add-host monocle_elastic_1:127.0.0.1 \
           --add-host crawler:127.0.0.1 \
           --add-host monocle_crawler_1:127.0.0.1 \
           --add-host web:127.0.0.1 \
           --add-host monocle_web_1:127.0.0.1 \
           --ulimit nofile=65535:65535 \
           --healthcheck-command 'curl --silent --fail localhost:9200/_cluster/health' \
           --healthcheck-interval 30s \
           --healthcheck-timeout 30s \
           --healthcheck-retries 3 \
           docker.elastic.co/elasticsearch/elasticsearch:7.10.1

podman run --name=monocle_api_1 \
           -d \
           -e CONFIG=/etc/monocle/config.yaml \
           -e ELASTIC_CONN=elastic:9200 \
           -e ALLOW_ORIGIN=http://localhost:3000 \
           -e CLIENT_ID= \
           -e CLIENT_SECRET= \
           -e REDIRECT_URL=http://localhost:9876/api/0/authorize \
           -e WEB_URL=http://localhost:3000 \
           -v ./etc:/etc/monocle:Z \
           --add-host api:127.0.0.1 \
           --add-host monocle_api_1:127.0.0.1 \
           --add-host elastic:127.0.0.1 \
           --add-host monocle_elastic_1:127.0.0.1 \
           --add-host crawler:127.0.0.1 \
           --add-host monocle_crawler_1:127.0.0.1 \
           --add-host web:127.0.0.1 \
           --add-host monocle_web_1:127.0.0.1 \
           --healthcheck-command 'python -c "import requests,sys; r=requests.get('"'"'http://localhost:9876/api/0/health'"'"'); print(r.text);"' \
           -p 9876:9876 \
           changemetrics/monocle_backend:latest uwsgi --uid guest --gid nogroup --http :9876 --socket :9877 --manage-script-name --mount /app=monocle.webapp:app

podman run --name=monocle_crawler_1 \
           -d \
           -e APP_ID= \
           -e APP_KEY_PATH=/etc/monocle/app_key.rsa \
           -v ./etc:/etc/monocle:Z \
           -v ./dump:/var/lib/crawler:Z \
           --add-host api:127.0.0.1 \
           --add-host monocle_api_1:127.0.0.1 \
           --add-host elastic:127.0.0.1 \
           --add-host monocle_elastic_1:127.0.0.1 \
           --add-host crawler:127.0.0.1 \
           --add-host monocle_crawler_1:127.0.0.1 \
           --add-host web:127.0.0.1 \
           --add-host monocle_web_1:127.0.0.1 \
           changemetrics/monocle_backend:latest monocle --elastic-conn elastic:9200 crawler --config /etc/monocle/config.yaml

podman run --name=monocle_web_1 \
           -d \
           -e REACT_APP_API_URL=http://localhost:9876 \
           -e REACT_APP_TITLE= \
           -p 0.0.0.0:3000:3000 \
           --add-host api:127.0.0.1 \
           --add-host monocle_api_1:127.0.0.1 \
           --add-host elastic:127.0.0.1 \
           --add-host monocle_elastic_1:127.0.0.1 \
           --add-host crawler:127.0.0.1 \
           --add-host monocle_crawler_1:127.0.0.1 \
           --add-host web:127.0.0.1 \
           --add-host monocle_web_1:127.0.0.1 \
           changemetrics/monocle_web:latest
```

I will try to workaround that issue in next commit.

2021-03-01 18:36 UTC, flepied requested changes
Would it be possible to add a github action to test it? I'm not confortable having no test for a new feature...

2021-03-02 09:34 UTC, morucci commented
I like the idea. Yes +1 for the test.

2021-03-02 10:08 UTC, morucci reviewed
I did an attempt to start with podman-compose but:

```
[fabien@localhost monocle]$ ~fabien/.local/bin/podman-compose up -d
using podman version: podman version 2.2.0-dev
Error: error inspecting object: unable to find a name and tag match for monocle_api in repotags: no such image
podman build -t monocle_api -f ./Dockerfile .
STEP 1: FROM python:3.9.1-alpine
Getting image source signatures
Copying blob 4f9b55c25d69 done  
Copying blob ba3557a56b15 done  
Copying blob 3123b734f0d4 done  
Copying blob ffd49e023448 done  
Copying blob 4d208653d5b9 done  
Copying config 430ddc6071 done  
Writing manifest to image destination
Storing signatures
STEP 2: WORKDIR /code
--> 922988f895e
STEP 3: COPY requirements.txt requirements.txt
--> ec3e482d81b
STEP 4: RUN apk --no-cache add build-base libffi-dev openssl-dev
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
(1/24) Installing libgcc (10.2.1_pre1-r3)
(2/24) Installing libstdc++ (10.2.1_pre1-r3)
(3/24) Installing binutils (2.35.1-r1)
(4/24) Installing libmagic (5.39-r0)
(5/24) Installing file (5.39-r0)
(6/24) Installing libgomp (10.2.1_pre1-r3)
(7/24) Installing libatomic (10.2.1_pre1-r3)
(8/24) Installing libgphobos (10.2.1_pre1-r3)
(9/24) Installing gmp (6.2.1-r0)
(10/24) Installing isl22 (0.22-r0)
(11/24) Installing mpfr4 (4.1.0-r0)
(12/24) Installing mpc1 (1.2.0-r0)
(13/24) Installing gcc (10.2.1_pre1-r3)
(14/24) Installing musl-dev (1.2.2-r0)
(15/24) Installing libc-dev (0.7.2-r3)
(16/24) Installing g++ (10.2.1_pre1-r3)
(17/24) Installing make (4.3-r0)
(18/24) Installing fortify-headers (1.1-r0)
(19/24) Installing patch (2.7.6-r6)
(20/24) Installing build-base (0.5-r2)
(21/24) Installing linux-headers (5.7.8-r0)
(22/24) Installing pkgconf (1.7.3-r0)
(23/24) Installing libffi-dev (3.3-r2)
(24/24) Installing openssl-dev (1.1.1j-r0)
Executing busybox-1.32.1-r3.trigger
OK: 213 MiB in 60 packages
--> a8206b59f22
STEP 5: RUN pip install -r requirements.txt
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 4.1 MB/s 
Collecting elasticsearch<8.0.0,>=7.0.0
  Downloading elasticsearch-7.11.0-py2.py3-none-any.whl (325 kB)
     |████████████████████████████████| 325 kB 7.1 MB/s 
Collecting flask
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 2.2 MB/s 
Collecting flask_cors
  Downloading Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting jsonschema
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
     |████████████████████████████████| 56 kB 2.8 MB/s 
Collecting pyyaml
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     |████████████████████████████████| 175 kB 5.5 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting tenacity
  Downloading tenacity-6.3.1-py2.py3-none-any.whl (36 kB)
Collecting authlib
  Downloading Authlib-0.15.3-py2.py3-none-any.whl (203 kB)
     |████████████████████████████████| 203 kB 713 kB/s 
Collecting Flask-Caching
  Downloading Flask_Caching-1.9.0-py2.py3-none-any.whl (33 kB)
Collecting uwsgi
  Downloading uWSGI-2.0.19.1.tar.gz (803 kB)
     |████████████████████████████████| 803 kB 6.8 MB/s 
Collecting iso8601
  Downloading iso8601-0.1.14-py2.py3-none-any.whl (9.5 kB)
Collecting dacite
  Downloading dacite-1.6.0-py3-none-any.whl (12 kB)
Collecting cryptography<=3.3.2
  Downloading cryptography-3.3.2.tar.gz (539 kB)
     |████████████████████████████████| 539 kB 5.0 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting cffi>=1.12
  Using cached cffi-1.14.5-cp39-cp39-linux_x86_64.whl
Collecting six>=1.4.1
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting urllib3<2,>=1.21.1
  Downloading urllib3-1.26.3-py2.py3-none-any.whl (137 kB)
     |████████████████████████████████| 137 kB 3.8 MB/s 
Collecting certifi
  Downloading certifi-2020.12.5-py2.py3-none-any.whl (147 kB)
     |████████████████████████████████| 147 kB 6.1 MB/s 
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Collecting click>=5.1
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 1.1 MB/s 
Collecting Jinja2>=2.10.1
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
     |████████████████████████████████| 125 kB 4.6 MB/s 
Collecting itsdangerous>=0.24
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Werkzeug>=0.15
  Downloading Werkzeug-1.0.1-py2.py3-none-any.whl (298 kB)
     |████████████████████████████████| 298 kB 6.8 MB/s 
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1.tar.gz (19 kB)
Collecting pyrsistent>=0.14.0
  Downloading pyrsistent-0.17.3.tar.gz (106 kB)
     |████████████████████████████████| 106 kB 5.4 MB/s 
Collecting attrs>=17.4.0
  Downloading attrs-20.3.0-py2.py3-none-any.whl (49 kB)
     |████████████████████████████████| 49 kB 4.5 MB/s 
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/site-packages (from jsonschema->-r requirements.txt (line 5)) (53.0.0)
Collecting idna<3,>=2.5
  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 2.2 MB/s 
Collecting chardet<5,>=3.0.2
  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)
     |████████████████████████████████| 178 kB 6.9 MB/s 
Building wheels for collected packages: cryptography, MarkupSafe, pyrsistent, pyyaml, uwsgi
  Building wheel for cryptography (PEP 517) ... done
  Created wheel for cryptography: filename=cryptography-3.3.2-cp39-cp39-linux_x86_64.whl size=362623 sha256=431720d8b9a774387ededf13663e982be0d86b36c1f5c1e804a3149f092a052e
  Stored in directory: /root/.cache/pip/wheels/0b/8b/61/b67c8d096e2e7ce198c09468a96a762be8ce29881268a000aa
  Building wheel for MarkupSafe (setup.py) ... done
  Created wheel for MarkupSafe: filename=MarkupSafe-1.1.1-cp39-cp39-linux_x86_64.whl size=17766 sha256=12f13c3df63a648798d542e1ee3e86bc8e28a21c308e1373a50a661ce378ce9a
  Stored in directory: /root/.cache/pip/wheels/e0/19/6f/6ba857621f50dc08e084312746ed3ebc14211ba30037d5e44e
  Building wheel for pyrsistent (setup.py) ... done
  Created wheel for pyrsistent: filename=pyrsistent-0.17.3-cp39-cp39-linux_x86_64.whl size=71761 sha256=29a3335e58fbc266e5877e9e83541c00e12e767b609fff43d0c01b038d29910b
  Stored in directory: /root/.cache/pip/wheels/00/cc/12/e712d3979a4aeee423b34a832d97c803e1a67659060315a7e0
  Building wheel for pyyaml (PEP 517) ... done
  Created wheel for pyyaml: filename=PyYAML-5.4.1-cp39-cp39-linux_x86_64.whl size=45641 sha256=46865898d1ddb43b00ddd3ea5875112d8bea0ca39637e556f17a4ca82ec895c8
  Stored in directory: /root/.cache/pip/wheels/b7/a5/c4/504d913c2a55bb09c607541578ec5f844d1ff33467abe93ba5
  Building wheel for uwsgi (setup.py) ... done
  Created wheel for uwsgi: filename=uWSGI-2.0.19.1-cp39-cp39-linux_x86_64.whl size=553307 sha256=4641a6a9781eb856e01ed91edaf5d1d1f7246ee1e6ac3378a2431195fdde40ba
  Stored in directory: /root/.cache/pip/wheels/17/66/cf/112237fefe0b8011e4a481305ba799b696ece8590219bd527f
Successfully built cryptography MarkupSafe pyrsistent pyyaml uwsgi
Installing collected packages: pycparser, MarkupSafe, Werkzeug, six, Jinja2, itsdangerous, click, cffi, urllib3, pyrsistent, idna, flask, cryptography, chardet, certifi, attrs, uwsgi, tenacity, requests, pyyaml, jsonschema, iso8601, flask-cors, Flask-Caching, elasticsearch, dacite, authlib
Successfully installed Flask-Caching-1.9.0 Jinja2-2.11.3 MarkupSafe-1.1.1 Werkzeug-1.0.1 attrs-20.3.0 authlib-0.15.3 certifi-2020.12.5 cffi-1.14.5 chardet-4.0.0 click-7.1.2 cryptography-3.3.2 dacite-1.6.0 elasticsearch-7.11.0 flask-1.1.2 flask-cors-3.0.10 idna-2.10 iso8601-0.1.14 itsdangerous-1.1.0 jsonschema-3.2.0 pycparser-2.20 pyrsistent-0.17.3 pyyaml-5.4.1 requests-2.25.1 six [...]

2021-03-04 08:37 UTC, danpawlik commented
There are two things left to do for podman-compose:
- podman-compose is ignoring .env file
- github workflow

2021-03-05 09:25 UTC, danpawlik commented
It waits for https://github.com/change-metrics/monocle/pull/313

2021-04-06 17:14 UTC, morucci commented
It seems podman 3 supports a solution to mimic the docker socket. So using docker-compose to deploy though podman might be better than using podman-compose. https://www.redhat.com/sysadmin/podman-docker-compose

For the moment I don't think we are going to support another deployment tool. So if docker-compose is compatible with podman then we should ensure it is and state it in the documentation of Monocle + validate it in the CI.

What do you think of closing this PR and open an issue on Monocle issue Tracker to describe that need and track the progress (by referring to the closed PR) ?

2021-04-13 07:41 UTC, morucci commented
Closing here. Please see my previous comment and create the related issue if needed. Thanks for your tries we podman-compose.

2021-04-13 07:41 UTC, closed without merging