Add data, etc and dump dir
change-metrics/monocle pull request #310
Opened 2021-02-25 17:39 UTC by danpawlik

Those directories are required for Monocle installation.

2021-02-28 20:03 UTC, flepied requested changes
Thanks for the PR. Could you fix `.github/workflows/validate-pr.yaml` to pass the CI?

2021-03-02 09:28 UTC, morucci requested changes

2021-03-02 09:28 UTC, morucci commented on .github/workflows/validate-pr.yaml
> +          mkdir -p data etc dump
Could you try to remove line 66 and 67 ?

2021-03-05 10:45 UTC, morucci approved these changes

2021-03-05 12:04 UTC, flepied approved these changes

2021-03-05 12:43 UTC, merged