[web] Use nginx to proxy pass the api
change-metrics/monocle pull request #355
Opened 2021-04-30 21:07 UTC by TristanCacqueray

This change simplifies deployment and enable more flexibility to
setup new api service:

- Add service port configuration to enable single host multi deployment
- Consolidate MONOCLE_URL into MONOCLE_PUBLIC_URL
- Remove CORS default configuration

This change also enables podman v3:
- Add missing compose healthcheck attribute
- Move the web dockerfile next to the compose file

Finally this change also improves the compose.dhall file by adding
helper functions.

Fixes #345

2021-05-03 13:01 UTC, morucci requested changes
Monocle web does not start in the start-with-podman script:
[fabien@ceres monocle]$ podman logs -f monocle_web
+ test -z ''
+ test -z 'Monocle Dev Podman deployment'
+ sed -i -e 's@__TITLE__@Monocle Dev Podman deployment@' /app/index.html
+ exec nginx -g 'daemon off;'
nginx: [emerg] host not found in upstream "api" in /etc/nginx/conf.d/monocle.conf:11

2021-05-03 13:16 UTC, TristanCacqueray commented on .env.sample
>  ###       MONOCLE_URL and MONOCLE_API_URL with your public ip address.
Done

2021-05-03 13:20 UTC, TristanCacqueray commented on README.md
> -- `MONOCLE_API_URL=<host or ip>` to configure the URL serving the API
Oops indead, we can drop it from the package. That's only needed to run the javascript development server with a custom api url.

2021-05-03 13:23 UTC, TristanCacqueray commented on contrib/start-with-podman.sh
> +export PUBLIC_ADDRESS=/
Done.

2021-05-03 13:24 UTC, TristanCacqueray commented on docker-compose.dhall
> -                      , { mapKey = "ALLOW_ORIGIN"
Maybe that could be useful to disable cors?

2021-05-03 13:25 UTC, TristanCacqueray commented on contrib/start-with-podman.sh
> +               -e REACT_APP_TITLE="Monocle Dev Podman deployment"
Oops, sorry, I didn't have enough disk space to both test podman and docker-compose.

2021-05-06 11:09 UTC, morucci approved these changes

2021-05-06 11:23 UTC, TristanCacqueray commented
:+1:

2021-05-06 11:30 UTC, merged