GHA: fix publishing workflow since container image renaming
change-metrics/monocle pull request #506
Opened 2021-07-22 14:00 UTC by morucci

2021-07-22 20:37 UTC, TristanCacqueray requested changes

2021-07-22 20:37 UTC, TristanCacqueray commented on .github/workflows/publish-master.yaml
> +          docker push quay.io/change-metrics/monocle_crawler-legacy:latest
We currently have monocle_api for the new api and macroscope, and monocle_backend for the legacy api and crawler. If you want to change the image, then we need to update the compose, but I think we can keep the current names.

2021-07-23 08:12 UTC, morucci commented
My bad, sorry. It should be better now. Thanks for the head up !

2021-07-23 11:57 UTC, TristanCacqueray approved these changes

2021-07-23 12:36 UTC, merged